// @generated by @mma/nx-plugin:service — DO NOT EDIT BY HAND
// To regenerate: nx g @mma/nx-plugin:service --domain=customer --entity=customer
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

import { ZodValidationPipe } from './zod-validation.pipe';
import { z } from 'zod';
import { BadRequestException } from '@nestjs/common';

describe('ZodValidationPipe', () => {
  it('returns parsed data on success', () => {
    const pipe = new ZodValidationPipe(z.object({ a: z.string() }));
    expect(pipe.transform({ a: 'x' })).toEqual({ a: 'x' });
  });

  it('throws BadRequestException on failure', () => {
    const pipe = new ZodValidationPipe(z.object({ a: z.string() }));
    expect(() => pipe.transform({ a: 1 })).toThrow(BadRequestException);
  });
});
