// @generated by @mma/nx-plugin:service — DO NOT EDIT BY HAND
// To regenerate: nx g @mma/nx-plugin:service --domain=customer --entity=customer
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

import { PipeTransform, BadRequestException } from '@nestjs/common';
import { ZodSchema } from 'zod';

export class ZodValidationPipe implements PipeTransform {
  constructor(private schema: ZodSchema) {}

  transform(value: unknown) {
    const result = this.schema.safeParse(value);
    if (!result.success) {
      throw new BadRequestException(result.error.issues);
    }
    return result.data;
  }
}
