/**
 * Generator file headers used to mark scaffold output as regenerable.
 *
 * Files written with one of these headers are surfaced to PR reviewers as
 * "regenerate, don't hand-edit" — paired with `linguist-generated=true` in
 * `.gitattributes` so GitHub auto-collapses them in diff view.
 */

export interface GeneratedHeaderOptions {
  /** Generator name, e.g. `@old-st/nx-plugin:event-handler`. */
  generator: string;
  /** Example regeneration command (single line). */
  command: string;
}

/** Returns a `//`-style header (TS, JS, CSS, etc.). */
export function tsGeneratedHeader(opts: GeneratedHeaderOptions): string {
  return `// @generated by ${opts.generator} — DO NOT EDIT BY HAND
// To regenerate: ${opts.command}
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

`;
}

/** Prepend a TS-style `@generated` header to file content. */
export function withGeneratedHeader(
  content: string,
  opts: GeneratedHeaderOptions,
): string {
  return tsGeneratedHeader(opts) + content;
}
