import type { Tree } from '@nx/devkit';

/**
 * Append a new TableConfig entry to scripts/setup-localstack.ts.
 *
 * This is a scoped string-edit (not a JSON edit) — the script is a TypeScript
 * file with a typed array literal. We locate the closing `];` of TABLE_CONFIGS
 * and inject a new entry just before it.
 *
 * Idempotent: returns false if a config with the same `tableName` env var is
 * already present.
 */
export const addLocalstackTable = (
  tree: Tree,
  options: {
    domainPascal: string; // "Shipping"
    domainConstant: string; // "SHIPPING"
    tableNameEnvVar: string; // "SHIPPINGS_DYNAMODB_TABLE_NAME"
    schemaName: string; // "ShipmentSchema"
    domainKebab: string; // "shipping"
    gsis: Array<{
      indexName: string; // "GSI1"
      hashKeyTemplate: string; // "SHIPPING#${status}"
      sortKeyTemplate?: string; // "${trackingNumber}"
      purpose: string; // "list by status sorted by tracking"
    }>;
  },
  scriptPath = 'scripts/setup-localstack.ts',
): boolean => {
  if (!tree.exists(scriptPath)) {
    throw new Error(`addLocalstackTable: ${scriptPath} not found.`);
  }
  const content = tree.read(scriptPath, 'utf-8') ?? '';
  if (content.includes(options.tableNameEnvVar)) {
    return false;
  }

  const attrSet = new Set<string>(['PK', 'SK']);
  for (const gsi of options.gsis) {
    attrSet.add(`${gsi.indexName}PK`);
    if (gsi.sortKeyTemplate) attrSet.add(`${gsi.indexName}SK`);
  }
  const attrLines = [...attrSet]
    .map((n) => `      { name: '${n}', type: 'S' as const },`)
    .join('\n');

  const gsiLines = options.gsis
    .map((g) => {
      const sortPart = g.sortKeyTemplate ? `, sortKey: '${g.indexName}SK'` : '';
      return `      { indexName: '${g.indexName}', hashKey: '${g.indexName}PK'${sortPart} }, // ${g.purpose}`;
    })
    .join('\n');

  const block = `  {
    // ── ${options.domainPascal.toUpperCase()} table (auto-generated by @mma/nx-plugin) ──
    // Driven by: ${options.tableNameEnvVar}
    // Schemas contributing GSIs:
    //   • ${options.schemaName} (packages/${options.domainKebab}-domain/src/infrastructure/schemas/${options.schemaName}.ts)
    tableName: process.env.${options.tableNameEnvVar} || '${options.domainConstant}',
    description: '${options.domainKebab}-domain — ${options.schemaName}',
    primaryHashKey: 'PK',
    primarySortKey: 'SK',
    attributeDefinitions: [
${attrLines}
    ],
    gsis: [
${gsiLines}
    ],
  },
`;

  // Locate `const TABLE_CONFIGS: TableConfig[] = [` then find its matching `];`.
  // Search for the assignment ` = [` so the type-annotation `[]` (e.g. `TableConfig[]`)
  // is not mistaken for the array opener.
  const startIdx = content.indexOf('const TABLE_CONFIGS');
  if (startIdx === -1) {
    throw new Error(
      `addLocalstackTable: TABLE_CONFIGS array not found in ${scriptPath}.`,
    );
  }
  const assignIdx = content.indexOf('= [', startIdx);
  if (assignIdx === -1) {
    throw new Error(
      `addLocalstackTable: could not find '= [' opener for TABLE_CONFIGS in ${scriptPath}.`,
    );
  }
  const arrayOpen = content.indexOf('[', assignIdx);
  // Walk to matching `];` accounting for nested braces.
  let depth = 0;
  let endIdx = -1;
  for (let i = arrayOpen; i < content.length; i++) {
    const ch = content[i];
    if (ch === '[' || ch === '{') depth++;
    else if (ch === ']' || ch === '}') {
      depth--;
      if (depth === 0) {
        endIdx = i;
        break;
      }
    }
  }
  if (endIdx === -1) {
    throw new Error(
      `addLocalstackTable: could not locate end of TABLE_CONFIGS array in ${scriptPath}.`,
    );
  }
  const before = content.slice(0, endIdx);
  const after = content.slice(endIdx);
  const updated = before.trimEnd() + '\n' + block + after;
  tree.write(scriptPath, updated);
  return true;
};

/**
 * Append a new QueueConfig entry to scripts/setup-localstack.ts.
 *
 * Idempotent: returns false if a config with the same `queueNameEnvVar` is
 * already present. Throws if the QUEUE_CONFIGS array cannot be located.
 */
export const addLocalstackQueue = (
  tree: Tree,
  options: {
    queueNameEnvVar: string; // "NOTIFICATIONS_SQS_QUEUE_NAME"
    queueNameDefault: string; // "notifications-events"
    description: string;
    fifo?: boolean;
  },
  scriptPath = 'scripts/setup-localstack.ts',
): boolean => {
  if (!tree.exists(scriptPath)) {
    throw new Error(`addLocalstackQueue: ${scriptPath} not found.`);
  }
  const content = tree.read(scriptPath, 'utf-8') ?? '';
  if (content.includes(`'${options.queueNameEnvVar}'`)) {
    return false;
  }

  const fifoLine = options.fifo ? `\n    fifo: true,` : '';
  const block = `  {
    queueNameEnvVar: '${options.queueNameEnvVar}',
    queueNameDefault: '${options.queueNameDefault}',
    description: '${options.description.replace(/'/g, "\\'")}',${fifoLine}
  },
`;

  const startIdx = content.indexOf('const QUEUE_CONFIGS');
  if (startIdx === -1) {
    throw new Error(
      `addLocalstackQueue: QUEUE_CONFIGS array not found in ${scriptPath}.`,
    );
  }
  const assignIdx = content.indexOf('= [', startIdx);
  if (assignIdx === -1) {
    throw new Error(
      `addLocalstackQueue: could not find '= [' opener for QUEUE_CONFIGS in ${scriptPath}.`,
    );
  }
  const arrayOpen = content.indexOf('[', assignIdx);
  let depth = 0;
  let endIdx = -1;
  for (let i = arrayOpen; i < content.length; i++) {
    const ch = content[i];
    if (ch === '[' || ch === '{') depth++;
    else if (ch === ']' || ch === '}') {
      depth--;
      if (depth === 0) {
        endIdx = i;
        break;
      }
    }
  }
  if (endIdx === -1) {
    throw new Error(
      `addLocalstackQueue: could not locate end of QUEUE_CONFIGS array in ${scriptPath}.`,
    );
  }
  const before = content.slice(0, endIdx);
  const after = content.slice(endIdx);
  const updated = before.trimEnd() + '\n' + block + after;
  tree.write(scriptPath, updated);
  return true;
};
