// @generated by @mma/nx-plugin:service — DO NOT EDIT BY HAND
// To regenerate: nx g @mma/nx-plugin:service --domain=customer --entity=customer
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

import { SetMetadata } from '@nestjs/common';

export const IS_PUBLIC_KEY = 'isPublic';
export const Public = () => SetMetadata(IS_PUBLIC_KEY, true);
