// @generated by @mma/nx-plugin:service — DO NOT EDIT BY HAND
// To regenerate: nx g @mma/nx-plugin:service --domain=customer --entity=customer
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

/**
 * JwtConfig — provider-agnostic JWT verification configuration.
 * Reads generic env vars that work with any OIDC-compliant provider.
 */
export class JwtConfig {
  static readonly jwksUri = process.env.JWT_JWKS_URI ?? '';
  static readonly issuer = process.env.JWT_ISSUER ?? '';
  static readonly userIdClaim =
    process.env.JWT_USER_ID_CLAIM ?? 'custom:userId';
  static readonly userRoleClaim =
    process.env.JWT_USER_ROLE_CLAIM ?? 'custom:userRole';

  static validate(): void {
    if (!this.jwksUri) {
      throw new Error('JWT_JWKS_URI must be set in non-local environments');
    }
    if (!this.issuer) {
      throw new Error('JWT_ISSUER must be set in non-local environments');
    }
  }
}
