import type { DomainNames } from '../../lib';
import type { FieldSpec } from '../../lib';

export interface DomainContext {
  domain: DomainNames;
  entity: DomainNames;
  fields: FieldSpec[];
  statuses: string[];
  /** True if statuses includes DELETED — controls soft-delete plumbing. */
  hasDeleted: boolean;
}

const renderFieldDecls = (fields: FieldSpec[]): string =>
  fields
    .map(
      (f) =>
        `    private ${f.name}: ${f.tsType}${f.optional ? ' | undefined' : ''},`,
    )
    .join('\n');

const renderFieldGetters = (fields: FieldSpec[], pascalEntity: string): string =>
  fields
    .map((f) => {
      const accessor = `get${f.name.charAt(0).toUpperCase()}${f.name.slice(1)}`;
      return `  ${accessor}(): ${f.tsType}${f.optional ? ' | undefined' : ''} {
    return this.${f.name};
  }`;
    })
    .join('\n\n');

const renderCreateProps = (fields: FieldSpec[]): string =>
  fields
    .map((f) => `    ${f.name}${f.optional ? '?' : ''}: ${f.tsType};`)
    .join('\n');

const renderCreateAssignments = (fields: FieldSpec[]): string =>
  fields.map((f) => `      props.${f.name},`).join('\n');

const renderReconstituteProps = (fields: FieldSpec[]): string =>
  fields
    .map((f) => `    ${f.name}${f.optional ? '?' : ''}: ${f.tsType};`)
    .join('\n');

const renderReconstituteAssignments = (fields: FieldSpec[]): string =>
  fields.map((f) => `      props.${f.name},`).join('\n');

export const renderEntity = (ctx: DomainContext): string => {
  const { entity, fields, statuses, hasDeleted } = ctx;
  const statusImport = statuses.length > 0
    ? `import { ${entity.pascal}Status, ${entity.pascal}StatusEnum } from '../constants';\n`
    : '';
  const exceptionsImport =
    `import { ${entity.pascal}AlreadyDeletedError${hasDeleted ? `, CannotUpdateDeleted${entity.pascal}Error` : ''} } from '../exceptions';\n`;

  const statusField = statuses.length > 0
    ? `    private ${entity.camel}Status: ${entity.pascal}Status,\n`
    : '';
  const statusGetter = statuses.length > 0
    ? `  get${entity.pascal}Status(): ${entity.pascal}Status {
    return this.${entity.camel}Status;
  }\n\n`
    : '';
  const statusInCreate = statuses.length > 0
    ? `      ${entity.pascal}StatusEnum.${statuses[0]},\n`
    : '';
  const statusInReconstitute = statuses.length > 0
    ? `      props.${entity.camel}Status,\n`
    : '';
  const statusReconstituteProp = statuses.length > 0
    ? `    ${entity.camel}Status: ${entity.pascal}Status;\n`
    : '';

  const markAsDeleted = hasDeleted
    ? `
  /**
   * Soft delete: mark as DELETED. Idempotent guard prevents double delete.
   */
  markAsDeleted(): void {
    if (this.${entity.camel}Status === ${entity.pascal}StatusEnum.DELETED) {
      throw new ${entity.pascal}AlreadyDeletedError();
    }
    this.${entity.camel}Status = ${entity.pascal}StatusEnum.DELETED;
    this.updatedAt = new Date().toISOString();
  }

  isDeleted(): boolean {
    return this.${entity.camel}Status === ${entity.pascal}StatusEnum.DELETED;
  }
`
    : '';

  return `${statusImport}${exceptionsImport}
/**
 * ${entity.pascal} Domain Entity
 *
 * Generated by @old-st/nx-plugin:domain. Add business rules, transitions,
 * and invariants here using the \`domain-business-rules\` skill.
 */
export class ${entity.pascal} {
  private constructor(
    private readonly ${entity.camel}Id: string | null,
${renderFieldDecls(fields)}
${statusField}    private readonly dateCreated: string,
    private updatedAt: string,
  ) {}

  /**
   * Factory: Create a new ${entity.camel} (not yet persisted).
   */
  static create(props: {
${renderCreateProps(fields)}
  }): ${entity.pascal} {
    const now = new Date().toISOString();
    return new ${entity.pascal}(
      null,
${renderCreateAssignments(fields)}
${statusInCreate}      now,
      now,
    );
  }

  /**
   * Factory: Reconstitute from persistence.
   */
  static reconstitute(props: {
    ${entity.camel}Id: string;
${renderReconstituteProps(fields)}
${statusReconstituteProp}    dateCreated: string;
    updatedAt: string;
  }): ${entity.pascal} {
    return new ${entity.pascal}(
      props.${entity.camel}Id,
${renderReconstituteAssignments(fields)}
${statusInReconstitute}      props.dateCreated,
      props.updatedAt,
    );
  }
${markAsDeleted}
  // ── Getters ────────────────────────────────────────────────────────────
  get${entity.pascal}Id(): string | null {
    return this.${entity.camel}Id;
  }

${renderFieldGetters(fields, entity.pascal)}

${statusGetter}  getDateCreated(): string {
    return this.dateCreated;
  }

  getUpdatedAt(): string {
    return this.updatedAt;
  }
}
`;
};

export const renderEntitySpec = (ctx: DomainContext): string => {
  const { entity, fields } = ctx;
  const sampleProps = fields
    .filter((f) => !f.optional)
    .map((f) => {
      const sample =
        f.type === 'string'
          ? `'sample-${f.name}'`
          : f.type === 'number'
            ? '1'
            : f.type === 'boolean'
              ? 'false'
              : 'new Date()';
      return `      ${f.name}: ${sample},`;
    })
    .join('\n');

  return `import { ${entity.pascal} } from './${entity.kebab}.entity';

describe('${entity.pascal}', () => {
  it('creates an entity with a null id and matching timestamps', () => {
    const ${entity.camel} = ${entity.pascal}.create({
${sampleProps}
    });
    expect(${entity.camel}.get${entity.pascal}Id()).toBeNull();
    expect(${entity.camel}.getDateCreated()).toBe(${entity.camel}.getUpdatedAt());
  });
});
`;
};

export const renderStatusesConst = (ctx: DomainContext): string => {
  const { entity, statuses } = ctx;
  const arrayLiteral = statuses.map((s) => `'${s}'`).join(', ');
  return `/**
 * ${entity.pascal} statuses — single source of truth.
 * Mirror this list in the contracts schema and the persistence schema.
 */
export const ${ctx.entity.constant}_STATUSES = [${arrayLiteral}] as const;

export type ${entity.pascal}Status = (typeof ${ctx.entity.constant}_STATUSES)[number];

export const ${entity.pascal}StatusEnum = ${ctx.entity.constant}_STATUSES.reduce(
  (acc, status) => ({ ...acc, [status]: status }),
  {} as Record<${entity.pascal}Status, ${entity.pascal}Status>,
);
`;
};

export const renderConstantsBarrel = (ctx: DomainContext): string => {
  return ctx.statuses.length > 0
    ? `export * from './${ctx.entity.kebab}-statuses';\n`
    : '';
};

export const renderDomainBarrel = (ctx: DomainContext): string => {
  const lines = ['export * from \'./entities\';', "export * from './exceptions';"];
  if (ctx.statuses.length > 0) lines.unshift("export * from './constants';");
  return lines.join('\n') + '\n';
};

export const renderEntitiesBarrel = (ctx: DomainContext): string =>
  `export * from './${ctx.entity.kebab}.entity';\n`;

export const renderDomainExceptions = (ctx: DomainContext): string[][] => {
  const { entity, hasDeleted } = ctx;
  const files: string[][] = [];

  // Always emit AlreadyDeleted (used by entity)
  files.push([
    `${entity.kebab}-already-deleted.error.ts`,
    `export class ${entity.pascal}AlreadyDeletedError extends Error {
  constructor() {
    super('${entity.pascal} is already deleted');
    this.name = '${entity.pascal}AlreadyDeletedError';
  }
}
`,
  ]);

  if (hasDeleted) {
    files.push([
      `cannot-update-deleted-${entity.kebab}.error.ts`,
      `export class CannotUpdateDeleted${entity.pascal}Error extends Error {
  constructor(field: string) {
    super(\`Cannot update \${field} on a deleted ${entity.camel}\`);
    this.name = 'CannotUpdateDeleted${entity.pascal}Error';
  }
}
`,
    ]);
  }

  return files;
};

export const renderDomainExceptionsBarrel = (ctx: DomainContext): string => {
  const { entity, hasDeleted } = ctx;
  const lines = [`export * from './${entity.kebab}-already-deleted.error';`];
  if (hasDeleted)
    lines.push(`export * from './cannot-update-deleted-${entity.kebab}.error';`);
  return lines.join('\n') + '\n';
};

export const renderApplicationExceptions = (ctx: DomainContext): string[][] => {
  const { entity } = ctx;
  return [
    [
      'invalid-input.error.ts',
      `export class InvalidInputError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'InvalidInputError';
  }
}
`,
    ],
    [
      `${entity.kebab}-not-found.error.ts`,
      `export class ${entity.pascal}NotFoundError extends Error {
  constructor(identifier: string) {
    super(\`${entity.pascal} not found: \${identifier}\`);
    this.name = '${entity.pascal}NotFoundError';
  }
}
`,
    ],
  ];
};

export const renderApplicationExceptionsBarrel = (ctx: DomainContext): string =>
  `export * from './invalid-input.error';
export * from './${ctx.entity.kebab}-not-found.error';
`;

export const renderApplicationBarrel = (ctx: DomainContext): string =>
  `export * from './use-cases';
export * from './interfaces/${ctx.entity.kebab}-repository.interface';
export * from './exceptions';
`;

export const renderRepositoryInterface = (ctx: DomainContext): string => {
  const { entity, statuses } = ctx;
  const statusType = statuses.length > 0 ? `${entity.pascal}Status` : 'string';
  const statusImport =
    statuses.length > 0
      ? `import { ${entity.pascal}Status } from '../../domain/constants';\n`
      : '';
  const listByStatusBlock =
    statuses.length > 0
      ? `
  /**
   * List ${entity.camelPlural} by status with cursor-based pagination.
   */
  abstract listByStatus(
    ${entity.camel}Status: ${statusType},
    limit?: number,
    direction?: string,
    nextCursorPointer?: string,
    prevCursorPointer?: string,
  ): Promise<IPaginatedResponse<${entity.pascal}>>;
`
      : '';

  return `import { IPaginatedResponse } from '@old-st/common';
${statusImport}import { ${entity.pascal} } from '../../domain/entities';

export abstract class I${entity.pascal}Repository {
  abstract save(${entity.camel}: ${entity.pascal}): Promise<${entity.pascal}>;

  abstract findById(${entity.camel}Id: string): Promise<${entity.pascal} | null>;
${listByStatusBlock}}
`;
};

export const renderUseCasesBarrel = (): string =>
  '// use cases registered here by the @old-st/nx-plugin:use-case generator\n';
