import { OrderStatus, OrderStatusEnum } from '../constants';
import {
  CustomerIdRequiredError,
  CannotModifyNonDraftOrderError,
  OrderItemNotFoundError,
  OrderAlreadyHasPaymentError,
  PaymentAmountMismatchError,
  InvalidOrderStatusTransitionError,
  CannotConfirmEmptyOrderError,
  PaymentRequiredForConfirmationError,
  InvalidPaymentStateForConfirmationError,
  CannotCancelOrderError,
  CannotRefundOrderError,
  PriceDriftDetectedError,
  CannotFailValidationError,
  CannotApproveProductValidationError,
} from '../exceptions';
import { OrderItem } from './order-item.entity';
import { OrderPayment } from './order-payment.entity';

/**
 * Order Entity (Aggregate Root)
 * Contains business logic and rules for order management
 */
export class Order {
  private constructor(
    private readonly orderId: string | null,
    private customerId: string,
    private items: OrderItem[],
    private payment: OrderPayment | null,
    private orderStatus: OrderStatus,
    private totalAmount: number,
    private readonly dateCreated: string,
    private updatedAt: string
  ) {}

  /**
   * Factory: Create a new order (draft)
   */
  static create(props: { customerId: string }): Order {
    if (!props.customerId.trim()) {
      throw new CustomerIdRequiredError();
    }

    const now = new Date().toISOString();

    return new Order(
      null, // orderId generated by database
      props.customerId,
      [], // Empty items initially
      null, // No payment initially
      OrderStatusEnum.DRAFT,
      0,
      now,
      now
    );
  }

  /**
   * Factory: Reconstitute from database
   */
  static reconstitute(props: {
    orderId: string;
    customerId: string;
    items: OrderItem[];
    payment: OrderPayment | null;
    orderStatus: OrderStatus;
    totalAmount: number;
    dateCreated: string;
    updatedAt: string;
  }): Order {
    return new Order(
      props.orderId,
      props.customerId,
      props.items,
      props.payment,
      props.orderStatus,
      props.totalAmount,
      props.dateCreated,
      props.updatedAt
    );
  }

  /**
   * Business Logic: Add item to order
   */
  addItem(item: OrderItem): void {
    if (this.orderStatus !== OrderStatusEnum.DRAFT) {
      throw new CannotModifyNonDraftOrderError('add');
    }

    this.items.push(item);
    this.recalculateTotal();
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Remove item from order
   */
  removeItem(itemId: string): void {
    if (this.orderStatus !== OrderStatusEnum.DRAFT) {
      throw new CannotModifyNonDraftOrderError('remove');
    }

    this.items = this.items.filter((item) => item.getItemId() !== itemId);
    this.recalculateTotal();
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Update item quantity
   */
  updateItemQuantity(itemId: string, newQuantity: number): void {
    if (this.orderStatus !== OrderStatusEnum.DRAFT) {
      throw new CannotModifyNonDraftOrderError('update');
    }

    const item = this.items.find((i) => i.getItemId() === itemId);
    if (!item) {
      throw new OrderItemNotFoundError(itemId);
    }

    item.updateQuantity(newQuantity);
    this.recalculateTotal();
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Add payment to order
   */
  addPayment(payment: OrderPayment): void {
    if (this.payment !== null) {
      throw new OrderAlreadyHasPaymentError();
    }

    if (payment.getAmount() !== this.totalAmount) {
      throw new PaymentAmountMismatchError();
    }

    this.payment = payment;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Confirm order
   * Requires PENDING status (products validated), items, and payment
   */
  confirmOrder(): void {
    if (this.orderStatus !== OrderStatusEnum.PENDING) {
      throw new InvalidOrderStatusTransitionError('confirm', 'pending');
    }

    if (this.items.length === 0) {
      throw new CannotConfirmEmptyOrderError();
    }

    if (!this.payment) {
      throw new PaymentRequiredForConfirmationError();
    }

    if (!this.payment.isSuccessful() && !this.payment.isPending()) {
      throw new InvalidPaymentStateForConfirmationError();
    }

    // Price drift guard: block confirmation if any item has drifted
    const hasDrift = this.items.some((item) => item.hasPriceDrift());
    if (hasDrift) {
      throw new PriceDriftDetectedError();
    }

    this.orderStatus = OrderStatusEnum.CONFIRMED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Start processing order
   */
  startProcessing(): void {
    if (this.orderStatus !== OrderStatusEnum.CONFIRMED) {
      throw new InvalidOrderStatusTransitionError('process', 'confirmed');
    }

    this.orderStatus = OrderStatusEnum.PROCESSING;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Ship order
   */
  ship(): void {
    if (this.orderStatus !== OrderStatusEnum.PROCESSING) {
      throw new InvalidOrderStatusTransitionError('ship', 'processing');
    }

    this.orderStatus = OrderStatusEnum.SHIPPED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Deliver order
   */
  deliver(): void {
    if (this.orderStatus !== OrderStatusEnum.SHIPPED) {
      throw new InvalidOrderStatusTransitionError('deliver', 'shipped');
    }

    this.orderStatus = OrderStatusEnum.DELIVERED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Cancel order
   */
  cancel(): void {
    if (
      this.orderStatus === OrderStatusEnum.DELIVERED ||
      this.orderStatus === OrderStatusEnum.REFUNDED ||
      this.orderStatus === OrderStatusEnum.VALIDATION_FAILED
    ) {
      throw new CannotCancelOrderError();
    }

    this.orderStatus = OrderStatusEnum.CANCELLED;

    // Cancel payment if exists
    if (this.payment && this.payment.isPending()) {
      this.payment.fail();
    }

    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Refund order
   */
  refund(): void {
    if (this.orderStatus !== OrderStatusEnum.DELIVERED) {
      throw new CannotRefundOrderError('can only refund delivered orders');
    }

    if (!this.payment || !this.payment.isSuccessful()) {
      throw new CannotRefundOrderError('no successful payment');
    }

    this.payment.refund();
    this.orderStatus = OrderStatusEnum.REFUNDED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Private: Recalculate order total
   */
  private recalculateTotal(): void {
    this.totalAmount = this.items.reduce(
      (sum, item) => sum + item.getSubtotal(),
      0
    );
  }

  /**
   * Business Logic: Approve product validation (DRAFT → PENDING)
   * Called when the product-event-handler confirms all items are valid.
   */
  approveProductValidation(): void {
    if (this.orderStatus !== OrderStatusEnum.DRAFT) {
      throw new CannotApproveProductValidationError();
    }

    this.orderStatus = OrderStatusEnum.PENDING;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Fail product validation (DRAFT → VALIDATION_FAILED, terminal)
   * Called when the product-event-handler finds invalid products.
   */
  failValidation(): void {
    if (this.orderStatus !== OrderStatusEnum.DRAFT) {
      throw new CannotFailValidationError();
    }

    this.orderStatus = OrderStatusEnum.VALIDATION_FAILED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Check order status
   */
  isDraft(): boolean {
    return this.orderStatus === OrderStatusEnum.DRAFT;
  }

  isConfirmed(): boolean {
    return this.orderStatus === OrderStatusEnum.CONFIRMED;
  }

  isDelivered(): boolean {
    return this.orderStatus === OrderStatusEnum.DELIVERED;
  }

  isCancelled(): boolean {
    return this.orderStatus === OrderStatusEnum.CANCELLED;
  }

  isPending(): boolean {
    return this.orderStatus === OrderStatusEnum.PENDING;
  }

  isValidationFailed(): boolean {
    return this.orderStatus === OrderStatusEnum.VALIDATION_FAILED;
  }

  // Getters
  getOrderId(): string | null {
    return this.orderId;
  }

  getCustomerId(): string {
    return this.customerId;
  }

  getItems(): OrderItem[] {
    return [...this.items]; // Return copy
  }

  getPayment(): OrderPayment | null {
    return this.payment;
  }

  getOrderStatus(): OrderStatus {
    return this.orderStatus;
  }

  getTotalAmount(): number {
    return this.totalAmount;
  }

  getDateCreated(): string {
    return this.dateCreated;
  }

  getUpdatedAt(): string {
    return this.updatedAt;
  }

}
