import { PaymentMethod, PaymentStatus, PaymentStatusEnum } from '../constants';
import {
  InvalidPaymentAmountError,
  InvalidPaymentStatusTransitionError,
} from '../exceptions';

/**
 * OrderPayment Entity
 * Represents payment information for an order
 */
export class OrderPayment {
  private constructor(
    private readonly paymentId: string | null,
    private paymentMethod: PaymentMethod,
    private amount: number,
    private paymentStatus: PaymentStatus,
    private transactionId: string | null,
    private readonly dateCreated: string,
    private updatedAt: string
  ) {}

  /**
   * Factory: Create a new payment
   */
  static create(props: {
    paymentMethod: PaymentMethod;
    amount: number;
  }): OrderPayment {
    // Business validation
    if (props.amount <= 0) {
      throw new InvalidPaymentAmountError();
    }

    const now = new Date().toISOString();

    return new OrderPayment(
      null, // paymentId generated by database
      props.paymentMethod,
      props.amount,
      PaymentStatusEnum.PENDING,
      null,
      now,
      now
    );
  }

  /**
   * Factory: Reconstitute from database
   */
  static reconstitute(props: {
    paymentId: string;
    paymentMethod: PaymentMethod;
    amount: number;
    paymentStatus: PaymentStatus;
    transactionId: string | null;
    dateCreated: string;
    updatedAt: string;
  }): OrderPayment {
    return new OrderPayment(
      props.paymentId,
      props.paymentMethod,
      props.amount,
      props.paymentStatus,
      props.transactionId,
      props.dateCreated,
      props.updatedAt
    );
  }

  /**
   * Business Logic: Authorize payment
   */
  authorize(transactionId: string): void {
    if (this.paymentStatus !== PaymentStatusEnum.PENDING) {
      throw new InvalidPaymentStatusTransitionError('authorize', 'pending');
    }
    this.paymentStatus = PaymentStatusEnum.AUTHORIZED;
    this.transactionId = transactionId;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Capture payment
   */
  capture(): void {
    if (this.paymentStatus !== PaymentStatusEnum.AUTHORIZED) {
      throw new InvalidPaymentStatusTransitionError('capture', 'authorized');
    }
    this.paymentStatus = PaymentStatusEnum.CAPTURED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Fail payment
   */
  fail(): void {
    if (this.paymentStatus === PaymentStatusEnum.CAPTURED || this.paymentStatus === PaymentStatusEnum.REFUNDED) {
      throw new InvalidPaymentStatusTransitionError('fail', 'non-captured/non-refunded');
    }
    this.paymentStatus = PaymentStatusEnum.FAILED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Refund payment
   */
  refund(): void {
    if (this.paymentStatus !== PaymentStatusEnum.CAPTURED) {
      throw new InvalidPaymentStatusTransitionError('refund', 'captured');
    }
    this.paymentStatus = PaymentStatusEnum.REFUNDED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Check if payment is successful
   */
  isSuccessful(): boolean {
    return this.paymentStatus === PaymentStatusEnum.CAPTURED;
  }

  isPending(): boolean {
    return this.paymentStatus === PaymentStatusEnum.PENDING;
  }

  // Getters
  getPaymentId(): string | null {
    return this.paymentId;
  }

  getPaymentMethod(): PaymentMethod {
    return this.paymentMethod;
  }

  getAmount(): number {
    return this.amount;
  }

  getPaymentStatus(): PaymentStatus {
    return this.paymentStatus;
  }

  getTransactionId(): string | null {
    return this.transactionId;
  }

  getDateCreated(): string {
    return this.dateCreated;
  }

  getUpdatedAt(): string {
    return this.updatedAt;
  }
}
