import {
  InvalidQuantityError,
  InvalidPriceError,
  ProductNameRequiredError,
} from '../exceptions';

/**
 * OrderItem Entity
 * Represents a single item in an order
 */
export class OrderItem {
  private constructor(
    private readonly itemId: string | null,
    private productId: string,
    private productName: string,
    private quantity: number,
    private price: number,
    private latestKnownPrice: number | null,
    private readonly dateCreated: string
  ) {}

  /**
   * Factory: Create a new order item
   */
  static create(props: {
    productId: string;
    productName: string;
    quantity: number;
    price: number;
  }): OrderItem {
    // Business validation
    if (props.quantity <= 0) {
      throw new InvalidQuantityError();
    }

    if (props.price < 0) {
      throw new InvalidPriceError();
    }

    if (!props.productName.trim()) {
      throw new ProductNameRequiredError();
    }

    const now = new Date().toISOString();

    return new OrderItem(
      null, // itemId generated by database
      props.productId,
      props.productName.trim(),
      props.quantity,
      props.price,
      null, // latestKnownPrice starts as null (no drift)
      now
    );
  }

  /**
   * Factory: Reconstitute from database
   */
  static reconstitute(props: {
    itemId: string;
    productId: string;
    productName: string;
    quantity: number;
    price: number;
    latestKnownPrice: number | null;
    dateCreated: string;
  }): OrderItem {
    return new OrderItem(
      props.itemId,
      props.productId,
      props.productName,
      props.quantity,
      props.price,
      props.latestKnownPrice,
      props.dateCreated
    );
  }

  /**
   * Business Logic: Update quantity
   */
  updateQuantity(newQuantity: number): void {
    if (newQuantity <= 0) {
      throw new InvalidQuantityError();
    }
    this.quantity = newQuantity;
  }

  /**
   * Business Logic: Update the latest known price from external source.
   * Used by async event handlers to flag price drift.
   */
  updateLatestKnownPrice(newPrice: number): void {
    this.latestKnownPrice = newPrice;
  }

  /**
   * Business Logic: Check if a price drift exists.
   * Drift exists when latestKnownPrice is set and differs from the snapshot price.
   */
  hasPriceDrift(): boolean {
    return this.latestKnownPrice !== null && this.latestKnownPrice !== this.price;
  }

  /**
   * Business Logic: Calculate subtotal
   */
  getSubtotal(): number {
    return this.quantity * this.price;
  }

  // Getters
  getItemId(): string | null {
    return this.itemId;
  }

  getProductId(): string {
    return this.productId;
  }

  getProductName(): string {
    return this.productName;
  }

  getQuantity(): number {
    return this.quantity;
  }

  getPrice(): number {
    return this.price;
  }

  getLatestKnownPrice(): number | null {
    return this.latestKnownPrice;
  }

  getDateCreated(): string {
    return this.dateCreated;
  }
}
