// @generated by @mma/nx-plugin:service — DO NOT EDIT BY HAND
// To regenerate: nx g @mma/nx-plugin:service --domain=customer --entity=customer
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

import { initTelemetry, correlationMiddleware } from '@mma/telemetry';
initTelemetry('customer-api-service');

import { Logger, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app/app.module';
import { DomainExceptionFilter } from './presentation';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.use(correlationMiddleware()); // MUST be first — generates/propagates correlationId
  app.setGlobalPrefix('api');
  app.enableCors({
    origin: process.env.FE_BASE_URL || 'http://localhost:4200',
    credentials: true,
  });
  app.useGlobalPipes(new ValidationPipe());
  app.useGlobalFilters(new DomainExceptionFilter());

  if (process.env.STAGE === 'local' || process.env.SWAGGER_ENABLED === 'true') {
    const builder = new DocumentBuilder()
      .setTitle(`CUSTOMER-API-SERVICE [${process.env.STAGE ?? 'local'}]`)
      .setDescription('CUSTOMER-API-SERVICE API')
      .setVersion('1.0')
      .addBearerAuth(
        {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          name: 'JWT',
          description: 'Enter JWT token',
          in: 'header',
        },
        'JWT-auth',
      );

    // In deployed environments the API Gateway routes traffic to this Lambda
    // under /${DOMAIN_PREFIX}, and Lambda Web Adapter strips that prefix
    // before forwarding to NestJS. Without addServer(), the Swagger UI's
    // "Try it out" button would call /api/... directly and miss the gateway
    // prefix → 404. DOMAIN_PREFIX is injected by Terraform; unset locally.
    if (process.env.DOMAIN_PREFIX) {
      builder.addServer(`/${process.env.DOMAIN_PREFIX}`);
    }

    const document = SwaggerModule.createDocument(app, builder.build());
    SwaggerModule.setup('swagger', app, document, { useGlobalPrefix: true });
  }

  const port = process.env.CUSTOMER_SERVICE_PORT || 8080;
  await app.listen(port);
  Logger.log(
    `🚀 CUSTOMER-API-SERVICE is running on: http://localhost:${port}/api`,
  );
}

bootstrap();
