// @generated by @mma/nx-plugin:service — DO NOT EDIT BY HAND
// To regenerate: nx g @mma/nx-plugin:service --domain=customer --entity=customer
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

export * from './controllers/customer.controller';
export * from './pipes/zod-validation.pipe';
export * from './filters/domain-exception.filter';
