// Product use cases
export * from './create-product/create-product.use-case';
export * from './get-product-by-id/get-product-by-id.use-case';
export * from './update-product-details/update-product-details.use-case';
export * from './update-product-price/update-product-price.use-case';
export * from './update-product-inventory/update-product-inventory.use-case';
export * from './activate-product/activate-product.use-case';
export * from './deactivate-product/deactivate-product.use-case';
export * from './discontinue-product/discontinue-product.use-case';
export * from './delete-product/delete-product.use-case';
export * from './list-products-by-status/list-products-by-status.use-case';
export * from './list-products-by-category/list-products-by-category.use-case';
export * from './search-products-by-name/search-products-by-name.use-case';
export * from './check-products-availability/check-products-availability.use-case';
