import { UserRole, UserRoleEnum, UserStatus, UserStatusEnum } from '../constants';
import {
  InvalidEmailFormatError,
  InvalidNameError,
  EmailAlreadyVerifiedError,
  CannotActivateNonPendingUserError,
  CannotActivateUnverifiedEmailError,
  CannotDeactivateDeletedUserError,
  UserAlreadyInactiveError,
  UserAlreadyDeletedError,
  CannotUpdateDeletedUserError,
  CannotChangeRoleOfDeletedUserError,
  UserAlreadyHasRoleError,
} from '../exceptions';

/**
 * User Domain Entity
 * Contains business logic and rules for user management
 */
export class User {
  private constructor(
    private readonly userId: string | null,
    private readonly email: string,
    private firstName: string,
    private lastName: string,
    private emailVerified: boolean,
    private userRole: UserRole,
    private userStatus: UserStatus,
    private data: { country?: string },
    private readonly dateCreated: string,
    private updatedAt: string
  ) {}

  /**
   * Factory: Create a new user (not yet persisted)
   */
  static create(props: {
    email: string;
    firstName: string;
    lastName: string;
    userRole?: UserRole;
    data?: { country?: string };
  }): User {
    // Business validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(props.email)) {
      throw new InvalidEmailFormatError();
    }

    if (props.firstName.trim().length === 0) {
      throw new InvalidNameError('First name');
    }

    if (props.lastName.trim().length === 0) {
      throw new InvalidNameError('Last name');
    }

    const now = new Date().toISOString();

    return new User(
      null, // userId generated by database
      props.email.toLowerCase().trim(),
      props.firstName.trim(),
      props.lastName.trim(),
      false, // New users start unverified
      props.userRole || UserRoleEnum.USER,
      UserStatusEnum.PENDING, // New users start pending
      props.data || {},
      now,
      now
    );
  }

  /**
   * Factory: Reconstitute entity from database
   */
  static reconstitute(props: {
    userId: string;
    email: string;
    firstName: string;
    lastName: string;
    emailVerified: boolean;
    userRole: UserRole;
    userStatus: UserStatus;
    data: { country?: string };
    dateCreated: string;
    updatedAt: string;
  }): User {
    return new User(
      props.userId,
      props.email,
      props.firstName,
      props.lastName,
      props.emailVerified,
      props.userRole,
      props.userStatus,
      props.data,
      props.dateCreated,
      props.updatedAt
    );
  }

  /**
   * Business Logic: Verify user's email
   */
  verifyEmail(): void {
    if (this.emailVerified) {
      throw new EmailAlreadyVerifiedError();
    }
    this.emailVerified = true;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Activate user account
   * Rules: Can only activate pending users with verified email
   */
  activate(): void {
    if (this.userStatus !== UserStatusEnum.PENDING) {
      throw new CannotActivateNonPendingUserError();
    }

    if (!this.emailVerified) {
      throw new CannotActivateUnverifiedEmailError();
    }

    this.userStatus = UserStatusEnum.ACTIVE;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Deactivate user account
   */
  deactivate(): void {
    if (this.userStatus === UserStatusEnum.DELETED) {
      throw new CannotDeactivateDeletedUserError();
    }

    if (this.userStatus === UserStatusEnum.INACTIVE) {
      throw new UserAlreadyInactiveError();
    }

    this.userStatus = UserStatusEnum.INACTIVE;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Soft delete user
   */
  markAsDeleted(): void {
    if (this.userStatus === UserStatusEnum.DELETED) {
      throw new UserAlreadyDeletedError();
    }

    this.userStatus = UserStatusEnum.DELETED;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Update user profile
   */
  updateProfile(firstName: string, lastName: string): void {
    if (this.userStatus === UserStatusEnum.DELETED) {
      throw new CannotUpdateDeletedUserError('profile');
    }

    if (firstName.trim().length === 0) {
      throw new InvalidNameError('First name');
    }

    if (lastName.trim().length === 0) {
      throw new InvalidNameError('Last name');
    }

    this.firstName = firstName.trim();
    this.lastName = lastName.trim();
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Update user data
   */
  updateData(data: { country?: string }): void {
    if (this.userStatus === UserStatusEnum.DELETED) {
      throw new CannotUpdateDeletedUserError('data');
    }

    this.data = { ...this.data, ...data };
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Business Logic: Change user role (admin action)
   */
  changeRole(newRole: UserRole): void {
    if (this.userStatus === UserStatusEnum.DELETED) {
      throw new CannotChangeRoleOfDeletedUserError();
    }

    if (this.userRole === newRole) {
      throw new UserAlreadyHasRoleError();
    }

    this.userRole = newRole;
    this.updatedAt = new Date().toISOString();
  }

  /**
   * Check if user can perform certain actions
   */
  isActive(): boolean {
    return this.userStatus === UserStatusEnum.ACTIVE;
  }

  isPending(): boolean {
    return this.userStatus === UserStatusEnum.PENDING;
  }

  isDeleted(): boolean {
    return this.userStatus === UserStatusEnum.DELETED;
  }

  isAdmin(): boolean {
    return this.userRole === UserRoleEnum.ADMIN;
  }

  // Getters (encapsulation)
  getUserId(): string | null {
    return this.userId;
  }

  getEmail(): string {
    return this.email;
  }

  getFirstName(): string {
    return this.firstName;
  }

  getLastName(): string {
    return this.lastName;
  }

  getFullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }

  isEmailVerified(): boolean {
    return this.emailVerified;
  }

  getUserRole(): UserRole {
    return this.userRole;
  }

  getUserStatus(): UserStatus {
    return this.userStatus;
  }

  getData(): { country?: string } {
    return { ...this.data };
  }

  getDateCreated(): string {
    return this.dateCreated;
  }

  getUpdatedAt(): string {
    return this.updatedAt;
  }

}
