// @generated by @mma/nx-plugin:service — DO NOT EDIT BY HAND
// To regenerate: nx g @mma/nx-plugin:service --domain=customer --entity=customer
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

import { AppController } from './app.controller';

describe('AppController', () => {
  it('returns ok on health', () => {
    expect(new AppController().health()).toEqual({ status: 'ok' });
  });
});
