// @generated by @mma/nx-plugin:service — DO NOT EDIT BY HAND
// To regenerate: nx g @mma/nx-plugin:service --domain=customer --entity=customer
// See .gitattributes (linguist-generated=true) and PULL_REQUEST_TEMPLATE.md.

import { Module } from '@nestjs/common';
import { APP_GUARD } from '@nestjs/core';
import { JwtAuthGuard } from '../presentation/guards/jwt-auth.guard';
import { CustomerModule } from '../modules/customer.module';
import { AppController } from './app.controller';

@Module({
  imports: [CustomerModule],
  controllers: [AppController],
  providers: [
    {
      provide: APP_GUARD,
      useClass: JwtAuthGuard,
    },
  ],
})
export class AppModule {}
